# Generated by Django 3.0.8 on 2020-07-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cod_de_barra', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=3000)),
                ('marca', models.CharField(max_length=500)),
                ('categoria', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=2)),
                ('fecha_vencimiento', models.DateField()),
                ('ubicacion', models.CharField(max_length=500)),
                ('proveedor', models.CharField(max_length=300)),
                ('observaciones', models.CharField(max_length=3000)),
            ],
        ),
    ]
